### ISSUE TITLE
Fluid paddings, margins, etc. possible?

### ISSUE THREAD

**Issue by hansipete** [davidhellmann/tailwindcss-fluid-type#12]
Hello there,

First of all — thank you for this plugin! <3

I'm asking myself how to deal with text that acts as button label, etc. For most of my projekts that would look like:
```
<a class="inline-flex justify-center border border-black p-4 rounded-md text-lg">Button</a>
```
In this case I'd would like to have the padding as a fluid as well to keep proportions. I found a workaround by setting the padding to an arbitrary like `p-[0.25em]` but I'm sure theres better ways...

All the best from Berlin,
Hans

**Comment by davidhellmann** [comment]
Hey Hans!

good to hear that you like it!
Regarding your question…

There was a similar issue #7 (can't link it from the iOS app)

In short… I played around with it but it's a bottomless pit. 

Hope that's fine
Cheers
David
