### ISSUE TITLE
Error if no values set

### ISSUE THREAD

**Issue by davidhellmann** [davidhellmann/tailwindcss-fluid-type#14]
![CleanShot 2022-10-20 at 17 16 15](https://user-images.githubusercontent.com/764292/196989105-962fcbb1-6fba-43e9-ac52-c96a75394d45.png)

**Comment by handplant** [comment]
Check this! [https://play.tailwindcss.com/pbRj4X34TM](https://play.tailwindcss.com/pbRj4X34TM)
Also the normal text is fluid, despite prefix!

**Comment by davidhellmann** [comment]
Should be fixed: https://play.tailwindcss.com/pbRj4X34TM
