### ISSUE TITLE
Only default settings work

### ISSUE THREAD

**Issue by sabiertas** [davidhellmann/tailwindcss-fluid-type#19]
I'm trying to customize the configuration, but it doesn't matter what values ​​I put, the default configuration always appears, is it possible to solve this? For example, I would like the text-base to be equal to 1rem in addition to customizing the scaling ratios. Thank you

**Comment by sabiertas** [comment]
https://play.tailwindcss.com/GdyDimvRvG?file=config
Here you can see the configuration, but no matter what values ​​I put, nothing happens

**Comment by davidhellmann** [comment]
Hey!

Sorry was a bit busy these days. 
I'll check that this week.

**Comment by davidhellmann** [comment]
@sabiertas, you have to move the settings like here: https://play.tailwindcss.com/7IhFaemG51?file=config

It's mentioned here: https://github.com/davidhellmann/tailwindcss-fluid-type/releases/tag/2.0.0

**Comment by sabiertas** [comment]
perfect! thank you so much

**Comment by davidhellmann** [comment]
You're welcome :  )
