### ISSUE TITLE
dependency issues with tailwindcss@3.0.0-alpha.2

### ISSUE THREAD

**Issue by md1440** [davidhellmann/tailwindcss-fluid-type#2]
Hi there,

just wanted to drop a note that I wanted to try your pluging and run it with the latest alpha and it would not install properly: 

# npm resolution error report

2021-12-08T10:20:58.372Z

While resolving: ---template-quote-generator@1.0.0
Found: tailwindcss@3.0.0-alpha.2
node_modules/tailwindcss
  dev tailwindcss@"^3.0.0-alpha.2" from the root project

Could not resolve dependency:
peer tailwindcss@">=2.0.0" from tailwindcss-fluid-type@1.3.1
node_modules/tailwindcss-fluid-type
  tailwindcss-fluid-type@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Thanks

Best Regards

Marc

**Comment by davidhellmann** [comment]
@md1440 I released a new version 1.3.2 should be fixed.
