### ISSUE TITLE
How to determine the array 'values'?

### ISSUE THREAD

**Issue by mdominguez** [davidhellmann/tailwindcss-fluid-type#20]
Hi David,
First of all, thank you for this plugin!

In my default Tailwind 'text-' classes I like to name them after the font-size they represent in px (eg: 'text-20' = 20px = 1.25rem)
So I renamed your example values array to:
`values: {
'20' : [2], // 1.25rem
}`
But I would like to do this for other font-sizes too that aren't in your example nor the tailwind defaults (like '32px' for example). So how do you calculate which value needs to be between brackets for '32' like [2] was for '20'?

Not so great at maths so probably not seeing something obvious here 😅 thank you!

**Comment by davidhellmann** [comment]
I haven't heard back, so I'll close. Let me know if there is something that needs to be clarified.
