### ISSUE TITLE
Default settings analog to tailwindcss defaults?

### ISSUE THREAD

**Issue by christianmagill** [davidhellmann/tailwindcss-fluid-type#25]
Much thanks for your work on this. It seems very powerful.

In the readme for the default configuration it mentions:

`This are the default settings and analog to the tailwindcss defaults`

When I apply these settings I get different font sizes at the max screen size than I do from the tailwindcss defaults.

Are these default values aligned at a midpoint? Is it possible to adjust the settings so they align at the max screen size?

After reading through the readme, I'm not quite sure what some of the settings do. Are there any resources you can point me to that would explain the relationships between fontSizeMin, fontSizeMax, ratioMin, and ratioMax?

Much thanks for any help you can provide!

**Comment by christianmagill** [comment]
Thanks for the explanation. I'm pretty new to the lingo. Do you think this package is a bad fit if I'd like to mimic the tailwind defaults at the max screen size?

**Comment by alban-ameti** [comment]
> I think it's nearly impossible to map the TW default 100%. The question is why do you try to achieve that and the other question is why do you need fluid type at all? The Fluid Type plugin is based on the modular scale approach: https://www.modularscale.com/

What bases and ratio is the modular scale based on?

**Comment by davidhellmann** [comment]
Not sure what you mean. But the ratio can be whatever you like. And for the base the same. The base is more or less a Multiplikator.
