### ISSUE TITLE
Tailwind CSS Vesion 3 Breaking Change

### ISSUE THREAD

**Issue by goxmedia** [davidhellmann/tailwindcss-fluid-type#3]
Upon upgrade to Tailwind CSS v.3.0, the following import is now breaking within tailwind.config.js: **require('tailwindcss-fluid-type');**.  Package.json has been updated to Tailwind v3.0.

Demo also breaks when chaning the Tailwind version to 3.0: https://play.tailwindcss.com/3LDf3gzbhb

Side Note: Thanks for your awesome work on this plugin. We absolutely love it.

**Comment by davidhellmann** [comment]
Hey, thank you!
It works on your local dev stuff not or just in the playground? 
Maybe it's not ready to use plugins for now.
Found this  issues: https://github.com/tailwindlabs/play.tailwindcss.com/issues/102 

Did the update on my boilerplate yesterday and works fine:
https://github.com/davidhellmann/craftcms-baukasten/commit/15de9eea3a0ee9ce3e055925a7ba87d8dbf827e0

Maybe you can share your a bit more details. 
Did you update the plugin to the  latest version 1.3.2?

**Comment by goxmedia** [comment]
Hi David,

Thanks for your reply. Appears to be related to the same issue as tailwindlabs/play.tailwindcss.com#102, but not sure. 

Yes, issue occurs on local dev and the playground.

<img width="1792" alt="Screen Shot 2021-12-11 at 8 26 23 AM" src="https://user-images.githubusercontent.com/89282/145684224-0ebb0dc5-6a86-4552-879f-3362132109a2.png">

<img width="1792" alt="Screen Shot 2021-12-11 at 8 30 09 AM" src="https://user-images.githubusercontent.com/89282/145684236-81d41624-7560-427a-a156-cdd09cc8bff8.png">

I also upgraded your plugin to v1.3.2. I also see that Tailwind has just been updated to v3.0.1, so I'm going to instal that and see if it resolves this issue. Thanks.

**Comment by goxmedia** [comment]
Same issue after upgrading Tailwind to v3.0.1. Might be a Tailwind thing like you said.

**Comment by davidhellmann** [comment]
Looks like this is a TS issue? 
Maybe a project config / vs code config thing?
Found this: https://github.com/tailwindlabs/tailwindcss-forms/issues/18#issuecomment-735448249

**Comment by goxmedia** [comment]
Thanks. I'll give that a try. Never had to do that before but based upon the link you shared but I'll give it a shot. Not sure why the playground would be affected though.

**Comment by davidhellmann** [comment]
I close this for now.
