### ISSUE TITLE
Demo in Tailwind Play is borked

### ISSUE THREAD

**Issue by RyanRoberts** [davidhellmann/tailwindcss-fluid-type#4]
[Fluid Type Live Demo](https://play.tailwindcss.com/3LDf3gzbhb) seems to be broken in all versions of TW 🤔

https://media.yep.digital/eOkWVY

**Comment by davidhellmann** [comment]
Yes, I know it's not working. It's on my list for next week I hope. Think its related to #3

**Comment by davidhellmann** [comment]
Have opened an issue at the tailwind play repo: [109](https://github.com/tailwindlabs/play.tailwindcss.com/issues/109)

**Comment by davidhellmann** [comment]
So, should work now: https://play.tailwindcss.com/TegGD6vkSM

**Comment by christianmagill** [comment]
@davidhellmann I think the demo link in the readme never got updated to the fixed version.

**Comment by davidhellmann** [comment]
@christianmagill oh no, good point. Fixed now! Thank you!
