### ISSUE TITLE
Clamp structure invalid property value

### ISSUE THREAD

**Issue by CzuidwijkRB** [davidhellmann/tailwindcss-fluid-type#5]
After installing the package and setting it up through the tailwind config it was creating the font size as following : 
font-size: clamp(20px) calc(20px + (30 - 20) * ((100vw - 320px) / (1230 - 320))), 30px);
![image](https://user-images.githubusercontent.com/85888727/147827208-e4cb6149-b162-4005-a787-a29f04fb915a.png)

It works perfectly fine whenever I change the value within the inspector tool : 
font-size: clamp(20px, calc(20px + (30 - 20) * ((100vw - 320px) / (1230 - 320))), 30px);
![image](https://user-images.githubusercontent.com/85888727/147827217-f403c83e-e5f4-4afb-89dd-9854d216f1f7.png)

My tailwind setup : 
![image](https://user-images.githubusercontent.com/85888727/147827260-a406b07f-7191-4418-a98d-25d3f0006283.png)

After digging around in the index.js I changed line 56 - 58 into 1 complete line : 
Before : 
![image](https://user-images.githubusercontent.com/85888727/147827236-3181b925-63b6-424d-ace1-03344958db80.png)

After :
![image](https://user-images.githubusercontent.com/85888727/147827158-0979ec0e-2ef2-41c6-ba71-9c3d2862de99.png)

This generated the right value for me.

Did I do something wrong or has this occurred before? Thanks in advance

**Comment by davidhellmann** [comment]
I will look into it the next days. Looks like the clamp in screen one is closed to early. Didn't run into this but we will see. Thanks for reporting.

**Comment by davidhellmann** [comment]
@CzuidwijkRB can you please try the new release (1.3.3). 
Tried it locally with your settings and have no problems. 

What browser do you use?
If it not works for you let me know.

**Comment by CzuidwijkRB** [comment]
I can confirm that it works now, thanks!

The issue occurred in Google Chrome, seems to be fine now!
