### ISSUE TITLE
Support for Padding, Margin?

### ISSUE THREAD

**Issue by niklasgrewe** [davidhellmann/tailwindcss-fluid-type#7]
Hi, thank you very much for creating this plugin. I know that this plugin was developed mainly for the font size. Would there still be the possibility to support padding and margin as well? That would be pretty handy, since the configuration would only need to be set once.

**Comment by davidhellmann** [comment]
Thought about it and discussed it with some people. I'm not sure at the moment. I'll think about it again. But when I think I release a different plugin. Most of the settings here are just useful for fonts. For paddings / margins I think it needs just this settings

min/max breakpoint
factor (default 2). 
prio (min or max)

what do you think?

**Comment by niklasgrewe** [comment]
glad to hear you're thinking about it again. Good idea to create a separate plugin for it. The settings you mentioned, I find so far sufficient. I would not need more in my projects. However, I always find that I need the following css code again and again, like this:

```html
<div class="max-w-[min(80vw,48rem)]" />
```

of course i can use arbitrary values, but would you have an idea how to include such css properties in the plugin, maybe like this?

```html
<div class="max-w-min min-80vw min-max-w-3xl" />
```
it would be cool, if we could write something dynamic and not static.

**Comment by davidhellmann** [comment]
I think depending on the settings it should looks like this:

```html

<div class="p-4 m-2" />
```

and the CSS output like this (with prio `min` in mind and factor 2):

```css
div {
  padding: calc(1rem, __dynamic_value__, 2rem);
}
```

So `p-4` is 1rem on min width and on max-width it's simple *2 and results in a `p-8` in real. 

The biggest problem here is its no possible to mix this values with fixed ones. And spacings creating a lot of classes. 
So I'm not sure how to handle that. Maybe `p-4` etc. are fluid and stuff like `p-[2rem]` is fixed? Prefixing can be a solution but again, this creates a lot of extra classes.

**Comment by niklasgrewe** [comment]
I agree with your idea. It is only important to me that I am able to set min and max values. But as you have shown it, that is enough for me.

Good that you say that with the spacing values. It's true, this creates again many new classes, which are not all necessarily needed. I had overlooked that. And to work with prefix, I think it's also not best idea.

I would be happy if you would implement it the way you showed it in your example, i.e. `p-4` for fluid and e.g. `p-[4rem]` for the fixed values.

**Comment by davidhellmann** [comment]
I'll close this for now. I think about it to create another plugin but for this one, less is more :)

**Comment by davidhellmann** [comment]
Hey @changethe 
Maybe you can have a look at this issue #22, and you can use this approach. I'll not include this in this plugin, and having a plugin that affects nearly the whole TailwindCSS config is not a good idea. I understand your thoughts about it, but in the past, we used this approach initialized by me, but the designers weren't happy with that. But anyway. Currently, I don't have time to build something like that. It needs much more effort to achieve this. It's not just margin and padding. Position transforms etc. etc.

**Comment by davidhellmann** [comment]
Thanks for sharing. Sure, with additional classes it's much easier as to overwrite the default spacing. But when you do it this way, you also need that stuff for spacing, positions, transforms etc. etc. Sure, you can also create these classes. But is it a good way to create a tailwind inside tailwind? :D For me there is just one solution to do something like that, and that is to overwrite the default tailwind logic for that stuff. But I wonder if that is the right way (maintaining, breaking changes etc).

I think the approach from #22 is much easier for that without adding additional classes. 
But feel free to update the issues, happy to hear how you handle it and how it work in the end.
